import type { Env } from '../index';

type Inquiry = {
  id: number;
  name: string;
  email: string;
  organization: string;
  phone: string | null;
  part_107: string | null;
  existing_clients: string | null;
  message: string | null;
  interest: string;
  status: string;
  created_at: string;
};

type Upload = {
  id: number;
  inquiry_id: number;
  filename: string;
  content_type: string;
  r2_key: string;
  lake_name: string | null;
  file_size_bytes: number;
  uploaded_at: string;
};

export function generateReportHtml(
  inquiry: Inquiry,
  uploads: Upload[],
  baseUrl: string
): string {
  const lakeName = uploads[0]?.lake_name || 'Pilot Lake';
  const imageRows = uploads
    .map(
      (u) => `
    <div class="image-card">
      <img src="${baseUrl}/api/v1/public/uploads/${u.id}" alt="${u.filename}" loading="lazy" />
      <div class="image-meta">
        <strong>${u.filename}</strong>
        <span>${formatBytes(u.file_size_bytes)} · ${new Date(u.uploaded_at).toLocaleString()}</span>
      </div>
    </div>
  `
    )
    .join('');

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LogicGate Lake Survey Report — ${escapeHtml(lakeName)}</title>
    <style>
      body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #1a1a1a; }
      h1 { color: #005f6b; border-bottom: 2px solid #00f2ff; padding-bottom: 0.5rem; }
      h2 { color: #005f6b; margin-top: 2rem; }
      .meta { background: #f4f4f4; border-radius: 12px; padding: 1.5rem; margin: 1.5rem 0; }
      .meta-row { display: flex; justify-content: space-between; padding: 0.4rem 0; border-bottom: 1px solid #e0e0e0; }
      .meta-row:last-child { border-bottom: none; }
      .label { font-weight: 600; color: #555; }
      .image-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; margin-top: 1rem; }
      .image-card { border: 1px solid #e0e0e0; border-radius: 12px; overflow: hidden; }
      .image-card img { width: 100%; height: 220px; object-fit: cover; display: block; }
      .image-meta { padding: 1rem; font-size: 0.9rem; }
      .image-meta strong { display: block; margin-bottom: 0.3rem; }
      .image-meta span { color: #666; }
      .placeholder { background: #fafafa; border: 2px dashed #ccc; border-radius: 12px; padding: 2rem; text-align: center; color: #666; }
      .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e0e0e0; font-size: 0.85rem; color: #666; }
    </style>
  </head>
  <body>
    <h1>LogicGate Lake Survey Report</h1>

    <div class="meta">
      <div class="meta-row"><span class="label">Lake / Organization</span><span>${escapeHtml(inquiry.organization || lakeName)}</span></div>
      <div class="meta-row"><span class="label">Pilot Partner</span><span>${escapeHtml(inquiry.name)}</span></div>
      <div class="meta-row"><span class="label">Email</span><span>${escapeHtml(inquiry.email)}</span></div>
      <div class="meta-row"><span class="label">Phone</span><span>${escapeHtml(inquiry.phone || 'Not provided')}</span></div>
      <div class="meta-row"><span class="label">Part 107</span><span>${escapeHtml(inquiry.part_107 || 'Not specified')}</span></div>
      <div class="meta-row"><span class="label">Existing lake clients</span><span>${escapeHtml(inquiry.existing_clients || 'Not specified')}</span></div>
      <div class="meta-row"><span class="label">Inquiry date</span><span>${new Date(inquiry.created_at).toLocaleString()}</span></div>
    </div>

    <h2>Partner Notes</h2>
    <p>${escapeHtml(inquiry.message || 'No notes provided.')}</p>

    <h2>GPS-Tagged Image Gallery</h2>
    ${uploads.length > 0 ? `<div class="image-grid">${imageRows}</div>` : '<div class="placeholder">No images uploaded yet.</div>'}

    <h2>Shoreline & Vegetation Observations</h2>
    <div class="placeholder">
      Observations will be added after the pilot flight and image review.
    </div>

    <h2>Recommended Actions</h2>
    <div class="placeholder">
      Action items will be added after the pilot flight and image review.
    </div>

    <div class="footer">
      Generated by LogicGate Lake Surveys · Pilot Report · ${new Date().toLocaleDateString()}
    </div>
  </body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

export async function fetchInquiryAndUploads(
  env: Env,
  inquiryId: number
): Promise<{ inquiry: Inquiry | null; uploads: Upload[] }> {
  const inquiry = await env.DB.prepare(
    'SELECT * FROM inquiries WHERE id = ?'
  ).bind(inquiryId).first<Inquiry>();

  if (!inquiry) {
    return { inquiry: null, uploads: [] };
  }

  const result = await env.DB.prepare(
    'SELECT * FROM uploads WHERE inquiry_id = ? ORDER BY uploaded_at ASC'
  ).bind(inquiryId).all<Upload>();

  return { inquiry, uploads: result.results || [] };
}
